<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	  
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>getback-mywpf</ToolCommandName>
    <PackageId>getback-mywpf</PackageId>
	  <Authors>SH</Authors>
	<Version>1.3.1</Version>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="foreign-files\1Cv8.cf" />
    <None Remove="README.md" />
    <None Remove="templates\AddOrder.xaml.cs.sbn" />
    <None Remove="templates\AddOrder.xaml.sbn" />
    <None Remove="templates\AddProductWindow.xaml.cs.sbn" />
    <None Remove="templates\AddProductWindow.xaml.sbn" />
    <None Remove="templates\Authorization.xaml.cs.sbn" />
    <None Remove="templates\Authorization.xaml.sbn" />
    <None Remove="templates\EditOrder.xaml.cs.sbn" />
    <None Remove="templates\EditOrder.xaml.sbn" />
    <None Remove="templates\EditProductWindow.xaml.cs.sbn" />
    <None Remove="templates\EditProductWindow.xaml.sbn" />
    <None Remove="templates\ItemEquipment.xaml.cs.sbn" />
    <None Remove="templates\ItemEquipment.xaml.sbn" />
    <None Remove="templates\MainWindow.xaml.cs.sbn" />
    <None Remove="templates\MainWindow.xaml.sbn" />
    <None Remove="templates\OrderWin.xaml.cs.sbn" />
    <None Remove="templates\OrderWin.xaml.sbn" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="foreign-files\1Cv8.cf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="README.md" Pack="true" PackagePath="\">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\AddOrder.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\AddOrder.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\AddProductWindow.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\AddProductWindow.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\Authorization.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\Authorization.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\EditOrder.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\EditOrder.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\EditProductWindow.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\EditProductWindow.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\ItemEquipment.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\ItemEquipment.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\MainWindow.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\MainWindow.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\OrderWin.xaml.cs.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="templates\OrderWin.xaml.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Scriban" Version="7.0.6" />
  </ItemGroup>
  <ItemGroup>
    <None Update="templates\AuthWindow.sbn">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>